import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";

import "./globals.css";
import RootLayoutClient from "./RootLayoutClient"; // Import the client-side component

const inter = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://utfs.io/f/9ed8be6b-0481-41f4-a655-abca230c5084-hru0oc.ico"
          sizes="any"
        />
      </head>

      <body className={inter.className}>
        <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
